name: Build

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Grant gradlew permission
        run: chmod +x gradlew
      - name: Build
        run: |
          ./gradlew assembleDebug
      - name: Store generated APK file
        uses: actions/upload-artifact@v1
        with:
          name: Shortcuts
          path: ./app/build/outputs/apk/debug/app-debug.apk